export const SPECIALIZZAZIONI_SPECIALISTI = [
  "Medicina interna",
  "Medicina d'emergenza-urgenza",
  "Geriatria",
  "Medicina dello sport e dell'esercizio fisico",
  "Medicina termale",
  "Oncologia medica",
  "Medicina di comunita e delle cure primarie",
  "Medicina e cure palliative",
  "Allergologia ed immunologia clinica",
  "Dermatologia e venereologia",
  "Ematologia",
  "Endocrinologia e malattie del metabolismo",
  "Scienza dell'alimentazione",
  "Malattie dell'apparato digerente",
  "Malattie dell'apparato cardiovascolare (Cardiologia)",
  "Malattie dell'apparato respiratorio",
  "Malattie infettive e tropicali",
  "Nefrologia",
  "Reumatologia",
  "Neurologia",
  "Neuropsichiatria infantile",
  "Psichiatria",
  "Pediatria",
  "Chirurgia generale",
  "Chirurgia pediatrica",
  "Chirurgia plastica, ricostruttiva ed estetica",
  "Ginecologia ed ostetricia",
  "Ortopedia e traumatologia",
  "Urologia",
  "Chirurgia maxillo-facciale",
  "Neurochirurgia",
  "Oftalmologia (Oculista)",
  "Otorinolaringoiatria",
  "Cardiochirurgia",
  "Chirurgia toracica",
  "Chirurgia vascolare",
  "Anatomia patologica",
  "Microbiologia e virologia",
  "Patologia clinica (biochimica clinica)",
  "Radiodiagnostica",
  "Radioterapia",
  "Medicina nucleare",
  "Anestesia, rianimazione, terapia intensiva e del dolore",
  "Audiologia e foniatria",
  "Medicina fisica e riabilitativa",
  "Farmacologia e tossicologia clinica",
  "Genetica medica",
  "Igiene e medicina preventiva",
  "Medicina del lavoro",
  "Medicina legale",
  "Statistica sanitaria e biometria",
];
