export const SPECIALIZZAZIONI_SPECIALISTI = [
  "Cardiologia",
  "Neurologia",
  "Pneumologia",
  "Gastroenterologia",
  "Reumatologia",
  "Endocrinologia",
  "Urologia",
  "Oculistica",
  "ORL",
  "Dermatologia",
  "Ortopedia",
  "Oncologia",
  "Ematologia",
  "Nefrologia",
  "Psichiatria",
  "Fisiatria",
  "Medicina Interna",
  "Infettivologia",
] as const;
